const alunos = [
    {
      matricula: "12345",
      periodo: "2023",
      nome: "João Silva",
      cpf: "111.222.333-44",
      telefoneContato: "(11) 99999-9999",
      professorID: "professorID_1",
      professorNome: "Professor 1",
      professorDisciplina: "Matemática",
      email: "joao@example.com",
      arquivado: false,
    },
    {
      matricula: "54321",
      periodo: "2024",
      nome: "Maria Oliveira",
      cpf: "444.555.666-77",
      telefoneContato: "(11) 88888-8888",
      professorID: "professorID_2",
      professorNome: "Professor 2",
      professorDisciplina: "História",
      email: "maria@example.com",
      arquivado: false,
    },
    {
      matricula: "98765",
      periodo: "2023",
      nome: "Pedro Souza",
      cpf: "777.888.999-00",
      telefoneContato: "(11) 77777-7777",
      professorID: "professorID_3",
      professorNome: "Professor 3",
      professorDisciplina: "Geografia",
      email: "pedro@example.com",
      arquivado: false,
    },
    {
      matricula: "56789",
      periodo: "2024",
      nome: "Ana Santos",
      cpf: "123.456.789-00",
      telefoneContato: "(11) 66666-6666",
      professorID: "professorID_4",
      professorNome: "Professor 4",
      professorDisciplina: "Ciências",
      email: "ana@example.com",
      arquivado: false,
    },
  ];
  
  export default alunos;
  