const pacientes = [
    {
      nome: "Luiza Silva",
      cpf: "111.222.333-44",
      dataDeNascimento: "1990-05-15",
      email: "luiza@example.com",
      telefoneContato: "(11) 99999-9999",
      sexo: "Feminino",
      estadoCivil: "Casada",
      religiao: "Cristã",
      rendaFamiliar: "Alta",
      profissao: "Advogada",
      naturalidade: "São Paulo",
      nacionalidade: "Brasileira",
      enderecoCep: "12345-678",
      enderecoLogradouro: "Rua ABC",
      enderecoBairro: "Centro",
      enderecoCidade: "São Paulo",
      enderecoUF: "SP",
      dataInicioTratamento: "2023-01-01",
      dataTerminoTratamento: "2023-12-31",
      quemEncaminhouID: "quemEncaminhouID_1",
      quemEncaminhouNome: "Encaminhador 1",
      tipoDeTratamento: "Fisioterapia",
      arquivado: false,
    },
    {
      nome: "Pedro Oliveira",
      cpf: "444.555.666-77",
      dataDeNascimento: "1985-08-20",
      email: "pedro@example.com",
      telefoneContato: "(11) 88888-8888",
      sexo: "Masculino",
      estadoCivil: "Solteiro",
      religiao: "Ateu",
      rendaFamiliar: "Média",
      profissao: "Engenheiro",
      naturalidade: "Rio de Janeiro",
      nacionalidade: "Brasileira",
      enderecoCep: "54321-876",
      enderecoLogradouro: "Av. XYZ",
      enderecoBairro: "Bela Vista",
      enderecoCidade: "Rio de Janeiro",
      enderecoUF: "RJ",
      dataInicioTratamento: "2023-02-01",
      dataTerminoTratamento: "2023-11-30",
      quemEncaminhouID: "quemEncaminhouID_2",
      quemEncaminhouNome: "Encaminhador 2",
      tipoDeTratamento: "Psicoterapia",
      arquivado: false,
    },
    {
      nome: "Ana Souza",
      cpf: "777.888.999-00",
      dataDeNascimento: "1998-12-10",
      email: "ana@example.com",
      telefoneContato: "(11) 77777-7777",
      sexo: "Feminino",
      estadoCivil: "Solteira",
      religiao: "Espírita",
      rendaFamiliar: "Baixa",
      profissao: "Estudante",
      naturalidade: "Belo Horizonte",
      nacionalidade: "Brasileira",
      enderecoCep: "98765-432",
      enderecoLogradouro: "R. Teste",
      enderecoBairro: "Liberdade",
      enderecoCidade: "Belo Horizonte",
      enderecoUF: "MG",
      dataInicioTratamento: "2023-03-01",
      dataTerminoTratamento: "2023-10-31",
      quemEncaminhouID: "quemEncaminhouID_3",
      quemEncaminhouNome: "Encaminhador 3",
      tipoDeTratamento: "Terapia Ocupacional",
      arquivado: false,
    },
    {
      nome: "Gustavo Santos",
      cpf: "123.456.789-00",
      dataDeNascimento: "1975-06-25",
      email: "gustavo@example.com",
      telefoneContato: "(11) 66666-6666",
      sexo: "Masculino",
      estadoCivil: "Divorciado",
      religiao: "Católica",
      rendaFamiliar: "Média",
      profissao: "Médico",
      naturalidade: "Recife",
      nacionalidade: "Brasileira",
      enderecoCep: "13579-246",
      enderecoLogradouro: "R. Principal",
      enderecoBairro: "Centro",
      enderecoCidade: "Recife",
      enderecoUF: "PE",
      dataInicioTratamento: "2023-04-01",
      dataTerminoTratamento: "2023-09-30",
      quemEncaminhouID: "quemEncaminhouID_4",
      quemEncaminhouNome: "Encaminhador 4",
      tipoDeTratamento: "Fonoaudiologia",
      arquivado: false,
    },
  ];
  
  export default pacientes;
  