const users = [
    {
      nome: "Admin User",
      cpf: 1234567890,
      role: "admin",
      matricula: 123,
      periodoCursado: 4,
      disciplina: "Biologia",
      idOrientador: 456,
      disciplinaMinistrada: "Química",
      idSecretaria: 789,
      senha: "senha123",
    },
    {
      nome: "Student User",
      cpf: 987654321,
      role: "student",
      matricula: 456,
      periodoCursado: 3,
      disciplina: "Matemática",
      idOrientador: 789,
      disciplinaMinistrada: null,
      idSecretaria: null,
      senha: "studentpass",
    },
    {
      nome: "Secretary User",
      cpf: 135792468,
      role: "secretary",
      matricula: null,
      periodoCursado: null,
      disciplina: null,
      idOrientador: null,
      disciplinaMinistrada: null,
      idSecretaria: 123,
      senha: "secretpass",
    },
    {
      nome: "Professor User",
      cpf: 246813579,
      role: "professor",
      matricula: null,
      periodoCursado: null,
      disciplina: "Física",
      idOrientador: null,
      disciplinaMinistrada: null,
      idSecretaria: null,
      senha: "professorpass",
    },
  ];
  
  export default users;
  